### ISSUE TITLE
함수형식으로 첫 번째 숙제 구현하기

### ISSUE THREAD

**Issue by soominpsy** [StudyGroupPKU/TESTs#15]
준호오빠가 제출한 숙제는, 함수형식으루 구현한 코드니까 관심있는 분들 한번 보도록 하세요.

https://github.com/StudyGroupPKU/TESTs/blob/master/junho/h180225_homework.py

**Comment by junholeephy** [comment]
def 형식으로 구현한 코드 입니다. 
나중에 def 는 많이 쓸 유형이라, 미리 익혀 두면 좋을것 같습니다!

제 코드 한번씩 다들 실행해 보시길 바래요~
