### ISSUE TITLE
한국어가 들어가는 파이썬 코딩에 대해서

### ISSUE THREAD

**Issue by paxpo** [StudyGroupPKU/TESTs#20]
코딩을 하면서 한국어가 들어갈 수도 있는 부분이 있는데, 한국어는 주석에만 들어갈 수 있는지 여러분과 토론해보고 싶습니다.

**Comment by junholeephy** [comment]
우선 파이썬 코드중에 print 하는 부분을 한국어로 작성 가능합니다 (하지만 추천하지 않습니다!!!)

예를 들면 print("안녕") 이런 형식으로요.
하지만 파이썬 파일 맨 앞부분에 이런 주석이 붙어야 합니다
"# -*- coding: UTF-8 -*-"  (쌍따옴표는 제거 하셔야 합니다)

예제 코드를 여기로 올려놓겠으니 참고 바랍니다 : https://github.com/StudyGroupPKU/TESTs/blob/master/junho/korean.py
다시 한번 알려드리지만, 영어 외에 다른언어(한국어,중국어 등)는 불가피한 상황이 아니면 사용하지 않기를 추천합니다!
