### ISSUE TITLE
오리진은 어떤식으로 업스트림 내용을 가져오나요??

### ISSUE THREAD

**Issue by manggny** [StudyGroupPKU/TESTs#25]
명령어들을 보면 업스트림 내용이나 오리진내용을 로컬로 가져오는거 같던데.. 오리진내용은 어떻게 업데이트 해줘야 하나요??

**Comment by junholeephy** [comment]
안녕 재근아, 내가 아는선에서 답변을 해볼께.
우선 우리가 로컬을 업데이트 하는 명령은 아래와 같아 ::
(1)  git fetch upstream :: 업스트림과 현 로컬과의 연관을 맺어준다
(2) git pull upstream master :: 연관을 맺어주었으니, 업스트림에 있는 변화를 내 로컬로 당겨달라(pull).
(3) git push :: 업스트림에 따라 변화된 로컬내용을 나의 origin으로 넣어(push)달라.

위 (1),(2)번의 명령어들로 로컬이 업스트림에 비해 뒤쳐진 commit(변화)들을 당겨올수 있게되. 즉, 로컬이 업데이트 되는거지.  그리고 (3)번의 명령어로 origin을 업데이트 시키는 거지.

영어로 설명하면 더 자세할수 있어 : If you take a look on your "origin" webpage, you are able to check this. There are 3 kinds of indication comparing origin with upstream : [1] your branch is even with upstream, [2] your branch is * commits behind comparing with upstream, [3] your branch is * commits ahead comparing with upstream. (most of the times, your branch status would be combination of [2] and [3])
 [1] even : upstream과 origin의 내용이 같다면(even), 업데이트를 할 필요가 없다 
 [2] behind : "git fetch upstream" & "git pull upstream master" & "git push". 처음에 말한 (1),(2),(3) 내용 참조.
[3] ahead : 몇개의 업데이트가 본인이 로컬에서 일을 함으로 인해 생겼고, 그 업데이트들을 (예를들면) "git add","git commit", "git push" 명령어들로 로컬에 올림으로써, 업스트림과 비교 했을때, 몇개의 업데이트가 존재한다.
이럴때 PR(pull request)를 통해, 업스트림에 본인의 변화를 반영해달라 요청을 넣는다.

**Comment by junholeephy** [comment]
오리진 내용은 로컬의 명령어 들로 업데이트를 해줄수 밖에 없어, git add, git commit, git push 같은 명령어 들로 말이지.

**Comment by manggny** [comment]
음.. 그러면 업스트림에서 받아온걸 로컬에서 받아서 다시 오리진으로 업데이트 시켜야한다는 건가요? 그럼 제가 만든 파일이 아닌 다른 파일들도 커밋해야되는건가요??

**Comment by soominpsy** [comment]
업스트림->로컬->오리진 이 순서 맞는거 같아요. 커밋은 본인이 로컬에서 새로 만든 파일만 해주면 되는듯.
Git status 쳐보면 본인이 새로 만든 파일들이 빨간색으로 뜨는데 그중에 본인이 업뎃하고싶은 파일만 add랑 commit하면 됩니당

**Comment by junholeephy** [comment]
수민이 말이 맞아.  다른 사람의 커밋은 fetch upstream, pull upstream master할때 같이 업뎃 되는 거기 때문에, 다시 커밋할 필요가 없어. 대신 너가 그사람 파일에 수정을 했다면, 그리고 그 수정버전을 github에 올리고 싶다면, git add, git commit, git push 순서를 다시 해야 하는거구!

**Comment by manggny** [comment]
음 그러면 다른사람이 수정한거를 fetch나 pull로 로컬에 받아온거는 제가 따로 커밋을 안해도 나중에 오리진에 push할때 알아서 들어가는건가요?

**Comment by soominpsy** [comment]
네 맞아용!

**Comment by manggny** [comment]
ㅎㅎ 감사합니당

**Comment by manggny** [comment]
ㅎㅎ 감사합니당

**Comment by junholeephy** [comment]
나도 동의!
