### ISSUE TITLE
git rm을 통한 깔끔한 폴더관리!

### ISSUE THREAD

**Issue by paxpo** [StudyGroupPKU/TESTs#35]
git rm은 git에서 파일을 삭제할 때 사용하는 명령어입니다. 해당 명령어는 로컬에 위치한 파일 역시 삭제하여, git과 로컬에 있는 파일을 동시에 삭제하는 명령어라고 생각됩니다.
지금까지 파일들은 추가할때 "git add"를 사용했는데, "git rm"은 앞의 명령어와 같은 방법으로 써주시면 됩니다. git rm으로 삭제한 후에 git status를 통해 "deleted"라는 초록 글씨 표시를 볼 수 있습니다.
그 후로는 git commit -m 으로 이어지는 기존 방법을 통해 동기화 하면 됩니다.
이제 폴더를 깔끔하게 관리해 보아요!

**Comment by junholeephy** [comment]
민석아 코멘트 고마워! ㅎㅎㅎㅎ
git rm 는 민석이 말대로, 로컬에 있는 파일도 지울 뿐만 아니라, git 한테도 해당 파일을 지우라고 지시합니다.

**Comment by junholeephy** [comment]
또 이름을 바꾸고 싶은 파일이 있다면 "git mv" 쓰기를 추천 드립니다~~

**Comment by soominpsy** [comment]
오오~새로운 사실!! 감사감사
