### ISSUE TITLE
이미 올린 파일의 파일명 변경은 어떻게 하나요?

### ISSUE THREAD

**Issue by soominpsy** [StudyGroupPKU/TESTs#36]
로컬에서 새 파일을 만든 후, 이미 업로드를 했던 파일은 이름을 어떻게 바꾸면 되는걸까용?

**Comment by junholeephy** [comment]
좋은 질문이야 수민아~ ㅎㅎ
현파일 이름 : filename1.py,  원하는 파일이름: FILENAME.py
(1) git mv filename1.py FILENAME.py
(2) git commit -m "your message"
(3) git push
(4) make a pull request(PR)
(5) after your PR is merged, do "fetch" and "pull upstream"

**Comment by soominpsy** [comment]
오~되게 간단하네요 씨에씨에!
