### ISSUE TITLE
비교함수, 정의법def 질문 

### ISSUE THREAD

**Issue by soominpsy** [StudyGroupPKU/TESTs#43]
이번 숙제 '비교함수'와 'def' 관련 내용의 링크를 공유해주시거나 설명해주실 수 있나요?

**Comment by junholeephy** [comment]
우선 중국어로 설명된 링크 공유 합니다 "http://www.runoob.com/python/python-functions.html".
추가적인 문제 있으면, 코멘트 해주세요~!

**Comment by manggny** [comment]
한국어로도 답변을 드릴게요 ! 
우선 함수개념부터 설명드릴게요. 
프로그래밍 언어에서 함수는 수학에서 함수와 사실 일맥상통합니다.
예를들어, max(x,y) = x+y+1 이라는 함수가 있다고 가정해봅시다.
그럼 함수 이름은 max 이고, 参数는 x와y, 함수내용은 x+y+1이고, 그 값은 함수 내용의 결과값이 되겟죠!
파이선에서 함수 설정도 이와 같습니다.
def 함수이름(参数1，参数2) ：
      함수내용
       return 결과값  # 이 리턴 부분은 반환할 결과값이 없는경우 쓰지 않아도 됩니다.

이렇게 함수를 설정해주고 나면, 그 후엔 함수를 사용할 수 있습니다(같은 파일 안에서).
함수 사용은:
함수이름(参数1，参数2) 이런식으로 해주거나 반환값이 있는경우 a = 함수이름(参数1，参数2)이런식으로
하면 됩니다!

그럼 비교함수는 어떻게 하는지 간단히 말로만 표현해보면
def max(a,b):
     a가 b보다 크면, a를 출력한다
     b가 a보다 크면, b를 출력한다
     a와b가 같으면 두 수가 같다고 출력한다.

max(3,4)

이렇게 하면 두 수를 비교해서 큰 값을 출력하는 함수를 설정하고, 그 밑에 参数가 3,4로 하여 함수를 사용한 것이 됩니다!

혹시 더 궁금하시거나 이해안되는 부분 있으면 코멘트 해주세요 :)

**Comment by karin224** [comment]
저도 따로 찾아보고는 있었는데, 감사합니다.

그런데 반환값이라는게 어떤 의미인가요?

**Comment by manggny** [comment]
함수 설정할때 return뒤에 붙는 값으로, 계산 후 반환할 그 함수의 최종값입니다!
좀더 자세히 얘기하면 f(x)=x+1 이라는 함수가 있으면
f(3)를 실행하면 3+1이라는 과정을(함수 내용 부분) 거쳐서 4라는 결과값(return뒤에 붙는 값)이 나오죠.
프로그래밍 언어에서 return뒤에 붙는 값이 함수의 최종 값으로 반환되서 반환값이라고 한 거에요!
즉 a=f(3) 이렇게 하면 반환값이 4 이기때문에, a=4가 되겟죠!   
파이썬으로 위 함수를 실현해보면
def f(x) ：
y = x+1
return y
이렇게 설정한 뒤에
a = f(3) 하면 a=y(return할 값)이 되서 4 가 되는거죠.

**Comment by junholeephy** [comment]
정확하고 알아듣기 쉬운 답변이네요! 👍

**Comment by karin224** [comment]
덕분에 조금 알거 같아요. 감사합니다.
이건 좀 결이 다른 질문인데, 반환값을 사용하는 이유가 있나요? 
들어주신 예시에서 print 를 사용하는거나 return을 사용하는거나 차이가 없을 것 같은데...

**Comment by junhophy** [comment]
제가 한번 답변을 해볼께요.
반환값을 사용하는 이유는, 헤당함수로 부터 유의미한 값을 계산하고, 그 결과를 아래 계속될 코드에 반영하기 위함입니다.  

구체적인 예를 들면:
def func(a,b):
    if(a>b): return 10
    else return 0
이라고 정의 된 func함수가 있다고 치죠.

그러면 이런식으로 메인 코드를 짤수 있습니다 ::
a =3
b=18
c=func(a,b)
print(a+c)

여기서 func이라는 함수는 반환값이 존재 하기에,  func(a,b)의 값을 반환 및  c 라는 변량에 부여할수 있는것 입니다.

반면, 반환하지 않고 print만 포함 하는 함수는 이것이 불가능 하겠지요.(아래 예:)
def func2(a,b):
    if(a>b) print(10)
    else print(0)

이같은 경우엔 "c = func2(a,b)" 라는게 불가능 합니다, func2함수가 반환 하는 값이 없기 때문에, c라는 변량에 부여할 값이 없기 때문입니다.

**Comment by manggny** [comment]
작은 팁을 하나 덧붙이자면, 함수는 return을 만나면 그대로 반환값을 반환하고 종료하게 됩니다 :) 
그러니 필요하다면, return을 사용해서 일정 조건에서 함수를 종료시킬수도 있겠죠!

**Comment by karin224** [comment]
오, 알 것 같아요. 두분 감사드려요 ㅎㅎㅎ
