### ISSUE TITLE
Git 업데이트를 더 간단하게!

### ISSUE THREAD

**Issue by junholeephy** [StudyGroupPKU/TESTs#55]
지금 까지는 본인의 local을 upstream에 따라 업데이트 할때, 아래 명령들을 썼을것 입니다.
git fetch upstream
git pull upstream master
git push origin

이를 좀더 간단하게 하기 위해 bash script를 제공 합니다. 
이 파일은 저희 "TESTs"  repo에 있고, 이름은 "1_source_me.sh" 입니다.
vi 명령어로 해당 파일을 열어보면 위 3개 명령어들이 순차적으로 입력된것을 보실수 있습니다.
"1_source_me.sh"를 실행 하는 방법도 간단합니다 :: source 1_source_me.sh
이렇게 명령해주면, 위3개의 명령어들을 하나하나 실행 할필요 없이, 한번에 처리가 가능합니다!

궁금한점 있으면 질문해 주세요!

**Comment by soominpsy** [comment]
넵 좋은 정보 감사합니다!

**Comment by manggny** [comment]
와 감사합니다 ㅎㅎ

**Comment by karin224** [comment]
감사합니다 ㅎㅎ
