### ISSUE TITLE
Dictionary 형식에 관하여

### ISSUE THREAD

**Issue by karin224** [StudyGroupPKU/TESTs#60]
오늘 배운 Dictionary 형식에 대해서 몇가지 실험해보았습니다. 제가 질문했던 것도 포함해서요. 
그 내용을 공유합니다.

1. Dictionary 정의할 때
예시로 userNameAndAge={"Peter":38, "John"=51, "Alex"=13, "Alvin"="not available"} 이렇게 들어주셨었는데, 중괄호{} 안에서 정의할때에 등호(=)를 쓸 경우 SyntaxError: invalid syntax 에러가 납니다. 쌍점(:)으로만 가능한 것 같습니다.

2. Dictionary 형식도 index로 출력가능한가?
불가능합니다. 오로지 정의한 "string"으로만 가능합니다. 반대의 경우 그러니까 "John"=51이라고 하였을 때, 51을 넣으면 "John"이 나오는지도 궁금해서 해봤는데, 다 안되더라구요.  당연한 것일 수도 있지만, 쌍따옴표 제외한 John도 에러가 떴습니다.

다음은 제가 실험해 본 내용입니다. 직접 해보셔도 되지만, 시간절약을 위해... 첨부합니다.

userNameAndAge={"Peter":38, "John":51, "Alex":13, "Alvin":"not available"}
print(userNameAndAge["John"])
51

print(userNameAndAge[1])
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    print(userNameAndAge[1])
KeyError: 1

 print(userNameAndAge[John])
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    print(userNameAndAge[John])
NameError: name 'John' is not defined

간단하고, 어떻게 보면 이미 짐작했을 수도 있는 내용이지만 이왕 실제로 해본거 올려봅니다. 도움이 되었으면 좋겠네요 ㅎㅎ 덧붙일 내용이나, 잘못된 점이 있으면 알려주세요 ㅎㅎ

**Comment by junholeephy** [comment]
감사합니다! 
Dictionary는 저도 익숙하지 않은 형태라, index로 출력이 불가능하다는건 처음 알았네요!
다른분들도 참고 하시길 바래요!

**Comment by soominpsy** [comment]
와~ 감사합니다 ㅎㅎ 새로운 사실을 알게 되었네요!

**Comment by manggny** [comment]
감사합니다!! ㅎㅎ
