### ISSUE TITLE
20180303 스터디 모임 PDF 20쪽 수정합니다

### ISSUE THREAD

**Issue by junholeephy** [StudyGroupPKU/TESTs#62]
"list" interfaced "for" 부분을 수정합니다!
재근이가 지적해 줬듯이,  "for K in [10,20,30,40]" 이라고 하면 K는 매번 루프를 돌때 마다 '10','20','30','40' 이라는 값을  가지게 됩니다. "for" loop안에서 K에게 어떤 값을 부여하더라도, loop를 시작하는 위치에 오면 K 값이 "list"안의 값으로 초기화가 되네요!

**Comment by soominpsy** [comment]
넵넵

**Comment by karin224** [comment]
이상하다 생각했던 현상이 덕분에 이해가 되었습니다. 감사합니다 ㅎㅎ

**Comment by manggny** [comment]
감사합니다!! ㅎㅎ
