### ISSUE TITLE
이번 수민이가 낸 숙제가 어려우신 분들을 위해서!

### ISSUE THREAD

**Issue by junholeephy** [StudyGroupPKU/TESTs#66]
https://github.com/StudyGroupPKU/TESTs/blob/master/junho/h180304_list.py
위 링크는 제가 제출한 숙제의 링크 입니다. 대략적인 설명을 주석으로 달았으니 참고하세요!

우선, 이번 숙제는 난이도 면에서 이전과 차이가 있습니다. 이런 문제를 처음 접하시는 분들은 문제 해결시간이 상당할수 있다는 생각이 듭니다. 이번 숙제에 관해, 평소에 틈틈히 생각을 해보셔서, 기한안에 완성하시길 바랍니다!

이번 숙제를 푸는데 힌트를 드리고자 new issue를 열었습니다.
(1) 5의 배수 찾기 : 어떤수를 5로 나눴을때 나머지가 0인지 아닌지를 살펴보면, 5의 배수인지 아닌지 판단을 할수 있습니다. (나머지 계산법은, 3월3일 수민이 강의 내용을 참조 하세요^^)

(2) 작은수부터 큰 숫자 차례로 배열하기:
저 같은 경우 이렇게 생각했습니다 : 
    [1] 리스트를 input했을때, for loop를 돌려서 가장 작은 숫자를 찾고, 그 가장작은 숫자와 list의 첫번째 원소와 자리를 교환한다. 
    [2] 두번째 자리부터 for loop를 돌려서 가장 작은 숫자를 찾고, 그 가장작은 숫자와 list의 두번째 원소와 자리를 교환한다. 
   [3] 세번째 자리부터 for loop를 돌려서 가장 작은 숫자를 찾고, 그 가장작은 숫자와 list의 세번째 원소와 자리를 교환한다. 

이런식으로 모든원소에 관해 for loop를 돌리면, 순차적으로 정돈된 list를 얻을수 있게 됩니다.
구체적인 코드는 제가 제공한 링크에서 2~14번째 줄을 참조 하세요!

(3) (선택사항) 이렇게 함수형식으로 구현된 코드는 다시 사용 가능합니다 (35~38번째 줄). 그리고 임의의 list가 input되어도 순차적으로 배열시킨후 output 하는것을 코드를 돌리면 확인하실수 있습니다.  원하신다면, 임의의 list를 정의해서 코드 수정후, 코드가 정상적으로 일을 하는지 살펴 보는것도 공부에 도움이 될수 있다 생각이 듭니다! 

또, 의문점은 언제든지 물어봐 주세요~

**Comment by manggny** [comment]
음.. 저도 준호형이 위에 올린 방법대로 배열 코딩을 하긴 했지만! 배열하는 방법은 여러가지가 더 있습니다 :)
그중에 비교적 간단하고 대표적인걸 설명하면:
x = [1,2,3,4,5] 라고 할때, 우선 x[1]과x[2]를 비교해서 더 작은 수를 앞으로, 큰수를 뒤로 합니다.
그 다음에 다시 x[2]와 x[3]을 비교하는 식으로, 리스트 마지막까지 비교하고 위치를 교체해줍니다!
이렇게 붙어있는 두수끼리 비교해서 x길이 끝까지 가는것을 x의 길이만큼 반복하면, 모든 수가 큰 순서대로 배열이 되게 됩니다! 
이를 간단히 표현해보면
for i in range(len(x)):
     for j in range(len(x)):
         if x[j+1] is None:
               break
         else:
               swap(x[j],x[j+1])

뭐 이런식으로 되겠네요! 기본 사상만 적은거라 돌려도 돌아가지는 않을거에요 !
저도 이런식으로 하진 않았지만..ㅋㅋ 이렇게 순서 바꾸는법도 여러가지가 있고, 또 어느 방법이 더 
우수할지 계산해보면서 여러가지 코드를 짜보는 것도 도움이 될거라 생각합니다 ㅎㅎ

**Comment by junholeephy** [comment]
재근이의 코드 보시면, 재근이가 자세히 주석을 달아 놓았어요.
참고 하시면서 숙제 하시면 도움 많이 될거라 예상합니다!
