### ISSUE TITLE
함수 관련 질문입니다!

### ISSUE THREAD

**Issue by manggny** [StudyGroupPKU/TESTs#72]
음 갑자기 든 질문인데요!
혹시 함수에서 return값이 아닌 参数 자체를 바꿀수 있을까요?
예를들어
def aaa(x,y):
라는 함수가 있으면
return i 를 하면
q = aaa(x,y) = i가 될텐데 그게 아니고
x,y 자체를 바꾸는 방법은 없을까요?? 
예를들어 
def sort(x,y):
~~~(함수내용)
하면 return없이 sort(x,y)만해도 , x,y의 순서가 정렬되는 그렇게요!

**Comment by junholeephy** [comment]
응응 재근아 가능해. 
a  = [1,2,4,2,3]

def sort(list):
list.sort()

def(a)
print(a)

이런식으로 하면 a가 정렬되서 나올꺼야

**Comment by manggny** [comment]
오 방금해봣는데 리스트 형식 변량은 되는데 x=2 이런식으로 인트형 변량을 함수내에서 +2같이 값을 바꿔줘도 return이 아니면 값이 변하지 않네요!! 혹시 왜그런지 아시나요 ㅠ

**Comment by junholeephy** [comment]
정말그러네..  나도 몰랐어.. ㅎㅎ
분명 global 변량이랑 local 변량이랑 연관이 있을텐데, 너가 구글링해서 스터디 시간에 모두에게 알려줄래??

**Comment by manggny** [comment]
옙 ㅎㅎ 리스트는 자동으로 글로벌 변량이 되는건지.. 아니면 index방법인 것들은 바뀌는건지 헷갈리네요;; 제가 찾아보고 알게되면 다같이 공유하겠습니다 !

**Comment by junholeephy** [comment]
👍

**Comment by manggny** [comment]
list유형 글로벌 변량 관련해서 찾아보니 답이 나왔네요! 아래 링크에 자세히 설명되있습니다 ㅎㅎ
https://www.cnblogs.com/yym2013/p/5915980.html
일반 변량은 글로벌 변량으로 자동 설정이 되지 않아서, 굳이 바꾸고 싶다면 global 이라는 명령어도
声明해줘야 한다고 하네요! 감사합니다 ㅎㅎ
